# Generated by Django 2.2.4 on 2019-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DW', 'DWCC'), ('DP', 'Deneen Pottery'), ('O', 'Other')], max_length=2),
        ),
    ]
