# Generated by Django 2.2.4 on 2019-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191105_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DW', 'DWCC'), ('DP', 'Deneen Pottery'), ('BE', 'DWCC - Beaster')], max_length=2),
        ),
    ]
